recipe: pantheon
config:
  framework: drupal8
  xdebug: false

events:
  post-start:
    - appserver: composer install
  post-db-import:
    - appserver: drush cr

services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt-get install -y nodejs
      - npm install -global gulp-cli
    build:
      - composer global require "pantheon-systems/terminus:^2"
      - composer global require consolidation/cgr
      - cgr mglaman/drupal-check

tooling:
  npm:
    service: appserver
    cmd: cd /app/web/themes/THEME_NAME && npm
  gulp:
    service: appserver
    cmd: cd /app/web/themes/THEME_NAME && gulp
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
